site_name: Java Bootcamp
site_description: Javaを短期間で集中して学ぶための実践的な教科書プロジェクト - プログラミング経験者向けの体系的なカリキュラム
site_author: Java Bootcamp Team
site_url: https://nakata5577.github.io/java-bootcamp/
repo_url: https://github.com/nakata5577/java-bootcamp
repo_name: nakata5577/java-bootcamp
edit_uri: edit/main/docs/

# コピーライト
copyright: |
  Copyright &copy; 2025 <a href="https://github.com/nakata5577/java-bootcamp">Java Bootcamp</a> -
  このプロジェクトは教育目的で作成されています

theme:
  name: material
  language: ja
  icon:
    logo: material/school
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え
  features:
    # ナビゲーション
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    # 検索
    - search.suggest
    - search.highlight
    - search.share
    # コンテンツ
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.tooltips
    # TOC
    - toc.follow
    - toc.integrate

plugins:
  - search:
      lang:
        - ja
        - en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - tables
  - abbr
  - toc:
      permalink: true
      permalink_title: このセクションへのリンク

nav:
  - ホーム: index.md
  - Section 0 - イントロダクション:
    - 0-1. Javaとは: section-0/0-1-what-is-java.md
    - 0-2. 開発環境の構築: section-0/0-2-setup.md
    - 0-3. Hello, World!: section-0/0-3-hello-world.md
    - 0-4. プロジェクトの基本構造: section-0/0-4-project-structure.md
  - Section 1 - Javaの基本:
    - 1-1. 変数とデータ型: section-1/1-1-variables-and-types.md
    - 1-2. 演算子: section-1/1-2-operators.md
    - 1-3. 制御フロー: section-1/1-3-control-flow.md
    - 1-4. 配列: section-1/1-4-arrays.md
  - Section 2 - オブジェクト指向プログラミング:
    - 2-1. クラスとオブジェクト: section-2/2-1-classes-and-objects.md
    - 2-2. メソッドとコンストラクタ: section-2/2-2-methods-and-constructors.md
    - 2-3. カプセル化: section-2/2-3-encapsulation.md
    - 2-4. 継承: section-2/2-4-inheritance.md
    - 2-5. ポリモーフィズム: section-2/2-5-polymorphism.md
    - 2-6. 抽象クラスとインターフェース: section-2/2-6-abstract-and-interface.md
  - Section 3 - Javaの重要機能:
    - 3-1. 例外処理: section-3/3-1-exception-handling.md
    - 3-2. コレクションフレームワーク: section-3/3-2-collections.md
    - 3-3. ジェネリクス: section-3/3-3-generics.md
    - 3-4. ファイル入出力: section-3/3-4-file-io.md
  - Section 4 - モダンJava:
    - 4-1. ラムダ式: section-4/4-1-lambda.md
    - 4-2. Stream API: section-4/4-2-stream-api.md
    - 4-3. Optional: section-4/4-3-optional.md
  - Section 5 - 実践開発への一歩:
    - 5-1. ビルドツール入門: section-5/5-1-build-tools.md
    - 5-2. ユニットテスト: section-5/5-2-unit-testing.md
    - 5-3. データベース接続: section-5/5-3-jdbc.md
  - Section 6 - 総合演習:
    - 6. 総合演習プロジェクト: section-6/6-final-project.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nakata5577/java-bootcamp
      name: GitHub Repository
    - icon: fontawesome/brands/java
      link: https://www.oracle.com/java/
      name: Java公式サイト
  generator: false
  analytics:
    feedback:
      title: このページは役に立ちましたか？
      ratings:
        - icon: material/thumb-up-outline
          name: このページは役に立ちました
          data: 1
          note: フィードバックありがとうございます！
        - icon: material/thumb-down-outline
          name: このページは改善が必要です
          data: 0
          note: フィードバックありがとうございます。改善に努めます。
